"""קטלוג דגמי רכב ממשרד התחבורה

Revision ID: ca8b0ee2454d
Revises: e8fc2732b6e1
Create Date: 2026-08-29 22:46:27.900808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8b0ee2454d'
down_revision = 'e8fc2732b6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('model_code', sa.String(length=60), nullable=True),
    sa.Column('trim', sa.String(length=80), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('engine_volume', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(length=40), nullable=True),
    sa.Column('body', sa.String(length=60), nullable=True),
    sa.Column('horsepower', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'model', 'model_code', 'trim', name='uq_vehicle_model')
    )
    with op.batch_alter_table('vehicle_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_models_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_models_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_models_model_code'), ['model_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_models_year_from'), ['year_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_models_year_to'), ['year_to'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_models_year_to'))
        batch_op.drop_index(batch_op.f('ix_vehicle_models_year_from'))
        batch_op.drop_index(batch_op.f('ix_vehicle_models_model_code'))
        batch_op.drop_index(batch_op.f('ix_vehicle_models_model'))
        batch_op.drop_index(batch_op.f('ix_vehicle_models_make'))

    op.drop_table('vehicle_models')
    # ### end Alembic commands ###
