"""סכימה ראשונית: קטלוג, ארגונים ומשתמשים

Revision ID: e8b168d830d4
Revises: 
Create Date: 2026-08-29 20:11:03.577950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b168d830d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_category_name_parent')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manufacturers_name'), ['name'], unique=True)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=True)

    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=80), nullable=False),
    sa.Column('name_he', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('part_type', sa.String(length=60), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('vat_included', sa.Boolean(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=80), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=40), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parts_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_manufacturer_id'), ['manufacturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_name_en'), ['name_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_name_he'), ['name_he'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_part_number'), ['part_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_parts_part_type'), ['part_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('cross_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.String(length=80), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_brand', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'ref_number', 'ref_brand', name='uq_crossref')
    )
    with op.batch_alter_table('cross_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cross_references_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cross_references_ref_number'), ['ref_number'], unique=False)

    op.create_table('fitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('submodel', sa.String(length=120), nullable=True),
    sa.Column('engine_code', sa.String(length=60), nullable=True),
    sa.Column('engine_volume', sa.String(length=20), nullable=True),
    sa.Column('fuel', sa.String(length=40), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitments_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitments_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitments_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitments_year_from'), ['year_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitments_year_to'), ['year_to'], unique=False)

    op.create_table('part_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=80), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'supplier_id', name='uq_part_supplier')
    )
    with op.batch_alter_table('part_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_suppliers_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_suppliers_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_suppliers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_part_suppliers_part_id'))

    op.drop_table('part_suppliers')
    with op.batch_alter_table('fitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitments_year_to'))
        batch_op.drop_index(batch_op.f('ix_fitments_year_from'))
        batch_op.drop_index(batch_op.f('ix_fitments_part_id'))
        batch_op.drop_index(batch_op.f('ix_fitments_model'))
        batch_op.drop_index(batch_op.f('ix_fitments_make'))

    op.drop_table('fitments')
    with op.batch_alter_table('cross_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cross_references_ref_number'))
        batch_op.drop_index(batch_op.f('ix_cross_references_part_id'))

    op.drop_table('cross_references')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parts_part_type'))
        batch_op.drop_index(batch_op.f('ix_parts_part_number'))
        batch_op.drop_index(batch_op.f('ix_parts_name_he'))
        batch_op.drop_index(batch_op.f('ix_parts_name_en'))
        batch_op.drop_index(batch_op.f('ix_parts_manufacturer_id'))
        batch_op.drop_index(batch_op.f('ix_parts_is_active'))
        batch_op.drop_index(batch_op.f('ix_parts_category_id'))
        batch_op.drop_index(batch_op.f('ix_parts_barcode'))

    op.drop_table('parts')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))

    op.drop_table('suppliers')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))

    op.drop_table('organizations')
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturers_name'))

    op.drop_table('manufacturers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    # ### end Alembic commands ###
